language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
sudo: required
services:
- docker
notifications:
  email:
  - bilalwahla@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: VeFCCNsb3ijI98B6gRNoHrm/U8wmpMjdQuiC6isxuTAx0n9gEN5d2vepCiydCTeN+EO69jpQ2IkSZhxB0ZEpPlnWthLFXbu9a+pFnD0qT+IDlBvcB9lEeA9s1bySGlryBTHvN1/pw4Ws8B9DGAv32Zj5BColI1Xz1GEv2pVywVubwn56XJf2J0Jefd8yYJSUtbowM+bcfwPbeNecpoEzgVLE4A/WXmYXhFmEYKE2E3Ju8TC76FEvf1iuEPSSVkZzvYYTtO8Wek1+ZHsVyEWOHgk5RdMPjDVm61LwfL10/s44nWzqNmfNkL39tO1ptXBr2MqC3k2X/p9H9GZ5BhTwk6PksNiu9osAXQ0vJ6A/YzPFEodFBngPNSAivevTyaZNRztELvU8io07lmOB8ByUR+nMhC11PBCb30QxPRJcDm0oe2IzAvzx1m/Xr1pVagDdoHnY+ua1tHXI/aFYfd1iD06O5v8gtSaJc6mb17+ZDasnr2HqoHOQL/iZ2+Amwh++sSN5l2JnRxFW1cNGuPvOA+4cQ0KyQia6Fk82Xffljikh7FnsqApznMrGRE67ya/KRccEA/ARa1MFhtKfnyMRbWV7B/t9eS9DUTQDdb2uO/hzZoWZZbqcr5fKQw7IZMXxk7zobn7uY34ExXsIhPLoAeAM8jyEdcHN6ILTBRAhzYI=
  - secure: ZMwEGVhGyPth3I0ZMvvuxlzhRmmVCiLeM9setBnr+wT0E0P4YWzQWCJgBcwaTIzU8eH2HIGUGueYWvuYCz+HCJcJrOt54E+BTw6l/a+iS/WPYJIO5PVhIcPkhGuGIe/cV/LTY7O+YAxJG+mmXKbOTWUitwpdu3sjjheIQd0AP2dLWTJjsKlF6UCK/Ual4NFObs6+d9vt7mi27HLcO83n5mzmxz6ts+9L68eRBseF54AQ6bgdvRLVsG+W4W8zfFJeCEZEyEv0ycMfKPWe+LzRFh4ItZ/Bf4Y9IsQrz2TaDjoeLnWsHuaW8QFSBPft4nGaJclnlRCwKdXbVH5MV0BadEp9jBNpEkJz6DTgTHfEYEZ8uSyxJrRLbZfHcP5jj8k6wrxKVmUdqECAQzera4tSeMbvxFDNZrvoTivdTFgn+Kv55YxqWtxt2I5/QrrlLMnngHK/R/NdtVgJtCuy6AngFoZAefCgu7No7odlGLaXUiNzLrmsQoafedaN+Eo+i9491JaBIycnUxsrJOO9VgJkzsG69ki2h4i34DaXyDrhklHvzDzi4uydOQ/X/VCxD+JMZiUGos+ZJPCQwiJJNnJ0JbROp8q4sf+9W00NaPo6wpQysD3qkNkMLEEy+0gwWULY0ob+U38ooAkMgBAAObAT23GkQTI91oYfLDyaoPd//RY=
  - secure: ww+THCc+JTP9jF1mNPE0EdYrJ5x6ak419N7W+84mRdTYmvtAlGSNIIhXQnHsOXiO556SWltJnXe15N0NJRKwuCoHBvqT6NwvS+Br6QlpwedImM1vzXgW2TWppdM1j+hXL4vWatWkGWoLNJo4tqa+ugc/apktsdvd33p7iT++sDhD3ZxWpq0qsPKapE53JN9JB46OfckYuep75VaYHCNH9mkxagxJ9JeSpmsvhm88jCOeK1VcwrxV+mt0/vsqV51h4e7xuoL2DTRjqEXoldFp67zL815o8LrrC7SKgOa9BDifBcITbkUYsJtriRbf5eU45OHHbLICruYlVvvZMUsKex5vEeOSjOtJ17Z5Q4S7UuAsttggbvDDoeJYYehqqcMslB0vHGhevlueLPW7d1Pgt0s0pb1EDuasdEfGsJevxKFJnuNiSMFTejbZG6vnIb8enpmfWFurG/PORRI6gRO5k5PvzJ3SXjEqFew5iwWieaC6JPl5aDfUq7alN+OYZRK1Kptf6H0CM5S5aX53WyPhxNbHjPwSlmHPYArtU+6JLUOl2ZiUhTitQ+iRpC8RrVkwsW8yE5QvvB9qY6VB0Q6JyP52vIjm1E1P3qLUq++tpwlDJnMO7ffWcbfZidyEomJPQlX0Q3IMazF8dsauDisP1ZYVVxh3BKBljjA1GoT4A7I=
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- export BUILD_NAME=fhrs-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
