language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
sudo: required
services:
- docker
notifications:
  email:
  - bilalwahla@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: v7+hxkvaoMsxQ0tNlnFu3uY0bi9AIpa0z4ZV+85gBmHukmqV2G+dozrpHb/Wl92PpJqsopUNypMUnd4KfUAJBwaipBRur2Y7QNigt1OK3eRvpJeiaFcGS5dJPdf5hYt096pEpEVZNONFRuqcSwauSEuNr5qhpB7/zgO/XWCL6UTStZxlsd1bl0IVP7uAZ33idbLaXWzRDe58kciphUNV132Adm6MxFxl0QmJao5VOYVc6ZaGOfaw9AaiCSINYapaYmN/z8uXXuDAOFStIOv4WY4ik/MiA8+JW+nqAfa8k8U2puBsQ4aMTi0N/ch3VQZpDEDYgiP7eK95HTqjPahdX6fJWO9BsnymmoKQLgbMs1huN9kywL4MuFmn0fqfbqdA6ftQYW0VslYkIlJp+iL14s/GBO15fUh9IGH4BdCqydQVTCBCqqExeP+U6ffn+Z65SCsBbu3xTUjfsNTINrNDBrXBN+/ELYYbGYWaum2EOTga91kM0qTQp0zukwGX3RGJPupzwjROmUf8zB4DgNUsg7gLDEAqWeLEIzrr2jX4a2h+8fP4tqix8yLqg3SRZueNG+Jlou0v4nCSA6DbDhBfvJ3ORgSqz+/SOWSaR52ghoQLScTBIqV36vl9y5eez3XH+l+u4y4t0Jped4WT+TOW/XiihhbZsdCI1GDYIslWgVM=
  - secure: Mfws/1IvVL+KYGYq+vElrLbM2PekQ9xjFkPC/D5fdytInS5oPhrchqa0tLwfPHLBxra63kNs9fKYMXjHzsCJybFo5YH0lALdoe94AXJuCdVzJfy2xd4vYyfiHgG12o7OHJjYiG93qmIFznpCdvKuCYFDQ64g5RcE1/CLaaB+G/isjIFaPiv22jBnDHAbJ854PY8RyBMq4ZGynHaPpN2jUjIGTXmolhdhKfd8KAf44h75agPcBrmjIAvkJHULI42oMaCKQVFXapRdp5dHBbdVrVxmLeirVqMJ5en+YAM7T14K4iJzQZnPJ5AZrHXxotN5PK084kL4Ghuw9tXzRHdOLb4RZrMXsZymgI5yQidD2QE6G750OzRb8912mj2k0BS6to6quBYl5fiugY9aj9IGl+b7DFwkrUU05aIsPZD0TlfxDAGmDydXPgxm+/4lAa1/ZHeV8k++49HcWH/EWPPIal+jPIgBidoDNFQn5z9PVMSyhDOksLpDWDMyAremFygeDMqClHVLqcpeAynNgyZiHRRSm2kRC6cgZ5nZNp1XMsbFk9MueSpGibh6dWAQOVGTIed5pM6g5e3zzR+knM2FZLS2UpKKjdY9cWYcR1hJj12Ec46mSB47fDZtU2BtTiRwVkEzxdgTHErIl5HDdlcUd/BepijrT596WFgp7WewNHE=
  - secure: nIwb5PgvxTX1dEzqypPCQYrKr6JcDXKRsdkF796pD9p8Hw6FU9XZ0nylrXxr6F6dlbZiYVTBE1TGwXLoxzGBOj16hbS2IsVx+uUY2jtSnrJcKIHYhzCQjZKmZoGau/pgAlWHREYLPeUa2t64P7EpvGiTPWgpoGQXL5C6ODUrb6lMxQ6XbCuP4eXUL2ZdV2PaX23SfxumMKCZ1kkVAgN3A9zsh63ygwwhJ7vMcFVp/D05mTPqDc3wqjFEZ6bvhny3JBHJk89Vxzvv7j6uv7PQViPlTDBG30JdDwdRRJzCNe7NNRZvUIomgnciAhqPcYjVGueaX1Jr5C7PlkVF+Wp+TkQmzvJYke2gfMnhzk7s0fuA9xqFF/nB2f0P0OcY+IPam55thq2B0rC5jrjC6wn3KVepKKdWIV0VsRI+DvO0x5lwnW0mX6MS79xl4Lbh0z1B7LqYybw3s4dvFGfdiJScuUUqxHJbhF+7tTeEMrbykz9Mp+yri10JeWhgpZzf1ae9vAM5pr2J8HIPmpTMw9E30t0IzXupzPawIw5YVJFmWoGcYmlHWasDezPilW+4CIH2/Pt+CPwywlq4fGwf+1lWnQN0jx9HZ5J+9Plm/hwc+k710pOFQMYCJDkuWY2lvQVtTcXnAuZUG2rBjyKieqvBA6LxTaEkFza221Ywcr3/CWY=
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- export BUILD_NAME=fhrs-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/build_services.sh
- sh travis_scripts/tag_build.sh
- sh travis_scripts/deploy_to_docker_hub.sh
