language: groovy
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
sudo: required
services:
- docker
notifications:
  email:
  - bilalwahla@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
script:
- ./mvnw clean package
after_success:
- bash <(curl -s https://codecov.io/bash)
